/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./sections/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#e1e2eb",
        "on-primary-fixed": "#002021",
        "on-tertiary-fixed": "#410004",
        "primary": "#e9feff",
        "surface-container-highest": "#32353c",
        "glass-border": "rgba(255, 255, 255, 0.08)",
        "outline-variant": "#3a494a",
        "on-secondary-container": "#00311f",
        "on-tertiary": "#68000a",
        "primary-fixed-dim": "#00dce5",
        "secondary-fixed": "#6ffbbe",
        "surface-deep": "#0B0E14",
        "secondary-fixed-dim": "#4edea3",
        "surface-bright": "#363940",
        "surface-container": "#1d2026",
        "primary-fixed": "#63f7ff",
        "on-background": "#e1e2eb",
        "on-error": "#690005",
        "on-primary": "#003739",
        "surface-charcoal": "#0F172A",
        "tertiary-fixed-dim": "#ffb3ad",
        "tertiary-fixed": "#ffdad7",
        "surface": "#10131a",
        "on-primary-container": "#006c71",
        "on-secondary-fixed-variant": "#005236",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#930013",
        "inverse-surface": "#e1e2eb",
        "secondary": "#4edea3",
        "tertiary-container": "#ffd3cf",
        "surface-slate": "#1E293B",
        "surface-variant": "#32353c",
        "surface-tint": "#00dce5",
        "on-surface-variant": "#b9caca",
        "surface-container-lowest": "#0b0e14",
        "secondary-container": "#00a572",
        "surface-container-low": "#191c22",
        "inverse-on-surface": "#2e3037",
        "background": "#10131a",
        "glow-cyan": "rgba(0, 245, 255, 0.15)",
        "surface-container-high": "#272a31",
        "inverse-primary": "#00696e",
        "error": "#ffb4ab",
        "on-secondary": "#003824",
        "primary-container": "#00f5ff",
        "on-tertiary-container": "#bd1e26",
        "tertiary": "#fff8f7",
        "error-container": "#93000a",
        "outline": "#849495",
        "surface-dim": "#10131a",
        "on-primary-fixed-variant": "#004f53",
        "on-secondary-fixed": "#002113",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1440px",
        "margin-mobile": "16px",
        "base-unit": "8px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      animation: {
        "pulse-emerald": "pulse-emerald 2s infinite",
        "scan-line": "scan-line 4s linear infinite",
      },
      keyframes: {
        "pulse-emerald": {
          "0%": { boxShadow: "0 0 0 0 rgba(78, 222, 163, 0.4)" },
          "70%": { boxShadow: "0 0 0 10px rgba(78, 222, 163, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(78, 222, 163, 0)" },
        },
        "scan-line": {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(1000%)" },
        },
      },
    },
  },
  plugins: [],
};
